/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: [
    "acid",
    "aqua",
    "autumn",
    "black",
    "bumblebee",
    "business",
    "cmyk",
    "coffee",
    "corporate",
    "cupcake",
    "dark",
    "dracula",
    "emerald",
    "fantasy",
    "forest",
    "garden",
    "halloween",
    "lemonade",
    "lofi",
    "luxury",
    "night",
    "pastel",
    "retro",
    "synthwave",
    "valentine",
    "wireframe",
    "winter",
  ],
  plugins: [require("daisyui")],
};
